###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: djki
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=djki
        - MYSQL_DATABASE=djki
        - MYSQL_USER=djki
        - MYSQL_PASSWORD=djki21`21`
      ports:
        - "2015:3306"
      deploy:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

    webserver:
      image: nginx:alpine
      container_name: djki-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "2016:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: djki-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

